config {
  type: "incremental",
  schema: "citibike_stage_sql",
  name: "stg_sql_trips",
  description: "Cleaned up data for trips data source",
  tags: ["stage-sql_tag"],
  bigquery: {
    partitionBy: "DATE(load_time)",
    clusterBy: ["load_id"]
  },
  uniqueKey: [
    "user_id",
    "bike_id",
    "start_station_id",
    "end_station_id",
    "start_time"
  ]
}

${custom_macros.get_stage_table(
  dataform.projectConfig.vars.load_id,
  ref("src_sql_trips"),
  models.trips.columns
)}
